In [1]:
import numpy as np

In [2]:
L = range(10000)

%timeit [i ** 2 for i in L]

248 µs ± 4.05 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
L_new = np.arange(10000)

%timeit L_new ** 2 

2.52 µs ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
L_new.ndim

1

In [5]:
a = np.arange(1, 100, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
b = np.diag([1, 2, 3])
b

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
b[1, 0] = 100
b

array([[  1,   0,   0],
       [100,   2,   0],
       [  0,   0,   3]])

In [13]:
a_ = a[1:8]
a_
a__ = a[1:8:2]
a__ 

array([2, 4, 6, 8])